### ISSUE TITLE
Update options preferences for episode quality

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/Website#25] opened 2018-10-29 07:21 UTC
Updating beta site images and looking for changes

**Comment by Andy-ABTec** [comment] 2018-10-30 07:53
Updated all options images and added rss/json and display images

**Comment by Andy-ABTec** [comment] 2018-10-30 11:13
Re-ordered options to match tab bar

**Comment by SirSparkles** [comment] 2018-10-30 11:15
Would it help if I made a list of all the things that have changed recently?  

Release notes should be the base of all changes. Generally all enhancements and new features will need some sort of change to the website

**Comment by Andy-ABTec** [comment] 2018-10-30 17:17
Yes it would be useful please, Its taken me a couple of hours to figure out what has changed and update the options page structure and images, and I haven't even started on the context or the lhs navigation.

Talking about lhs navigation - that's next...

**Comment by Andy-ABTec** [comment] 2018-10-30 17:37
Navigation order now reflects the tab bar order and the main content order, just need to sort out/add the content changes, I say just...

**Comment by Andy-ABTec** [comment] 2018-10-30 18:05
Options>General updated
Options>Files and Folders updated 
Options>Automatic Export updated
Options>Scan Options checked, no changes found
Options>Folder Deleting checked, no changes found
Options>Media Centres checked, no changes found
Options>Search Folders checked, no changes found
Options>Torrents/NZB updated
Options>Tree Colouring checked, no changes found
Options>Bulk / Auto Add checked, no changes found
Options>Subtitles checked, no changes found

**Comment by SirSparkles** [comment] 2018-10-30 23:53
I made a few updates yesterday to go in the right direction. Probably need more detail in places though.

For example the logic around the upgrade files function:

1.  If we can't tell the length or quality from the file's metadata then we don't do anything (and ask the user)
1. If the present file is longer or better quality we leave it (and remove the new file)
1. if the new file is longer or better quality we replace it
1. if the new file has any of the key terms we use it to replace the existing
1. if the files are identical we do nothing (but remove the new one)
1. If we can't tell then we don't do anything and inform the user (via a new UI element)

**Comment by Andy-ABTec** [comment] 2018-10-31 07:25
Where would you put this content?

Is it "Features" (maybe a new section?) or with the options that control it?

**Comment by SirSparkles** [comment] 2018-10-31 11:15
Probably under features > Automation?

**Comment by Andy-ABTec** [comment] 2018-10-31 16:08
Cool, I'll pick it up when I've done with the options changes...

**Comment by Andy-ABTec** [comment] 2018-10-31 17:07
@MarkSummerville - quick question...

In "Display", "Seasons name:" and leading zero seems somewhat irrelevant?

Does it interact with the stuff in "Files and folders" or do they serve different purposes?

**Comment by SirSparkles** [comment] 2018-11-01 04:34
They are used less and less, especially now we have the custom template season format. These 2 fields are now only used to indicate what should be displayed in the UI when you expand a show in the Library.

**Comment by SirSparkles** [comment] 2018-11-01 04:36
PS - I think you might kill me. I'm struggling with room in the preferences screens and ended up changing the tabs to put them on the left. (I have not committed the change yet) just a head's up.

**Comment by Andy-ABTec** [comment] 2018-11-01 07:08
I'll only give you a light killing... :confounded:

Mussing with the tab order and updating the screen grabs doesn't take too long to fix-up,

It's having to go through each individual tab looking for changes against the previous versions when you say "I've updated the preferences" that's a real pain in the ass!

Viz https://github.com/TV-Rename/website/issues/25#issuecomment-434409397

PLEASE COMMIT IT SO I CAN SEE THE CHANGES, I wont go any further until I've seen what you've ~~broken~~ changed! 😉

**Comment by Andy-ABTec** [comment] 2018-11-01 18:59
Just had a look at "master" do you enjoy making my life difficult? :cry:

Seriously, is there any way of making the width of the panels narrower? otherwise trying to fit the new screen grabs in a web page or viewing a "preferences" page in TVR with so much blank real-estate is going to look really crappy! The Subtitles tab is a good example... 

Looking at them I would say that probably 40% of the right hand side of both the panels is empty(ish).
The vertical I can cope with using the normal ripped images and blurring the "un-selected tab" text.

Something Like this:

![image](https://user-images.githubusercontent.com/5175695/47873083-33810c00-de08-11e8-9589-aa928c6efda4.png)

Actually, looking at it again, I probably don't need to blur the text and the tab separators at all! It just needs to be narrower... much narrower!

This looks much better:

![image](https://user-images.githubusercontent.com/5175695/47874939-0e42cc80-de0d-11e8-8a29-1a6fd7a4f240.png)

I know you're still playing with it - it wreaks of the sketches done early this year when we were discussing V4 layout -  so I thought I'd get in quick before everything got set in stone...

**Comment by Andy-ABTec** [comment] 2018-11-01 19:24
Silly thoughts...

What about 3 rows of horizontal tabs instead of 2 or make the minimum window width wider by default?

Can you autofit the height?

If you want to stick with tabs on the lhs can you put an elevator bar of some description on them?

Sorry, one of my pet hates is looking at blank space in panes - seems such a waste!

**Comment by SirSparkles** [comment] 2018-11-02 17:12
Yeah - still tinkering. Have narrowed it up a lot - try the latest

**Comment by Andy-ABTec** [comment] 2018-11-02 19:43
That's much better, like the way the minimum width and height fits everything in but you can make it wider/taller if you want to!

**Comment by Andy-ABTec** [comment] 2018-11-02 19:55
Just pushed screen grabs for subtitles and automatic export (the two extreems) out to the beta site so you can see how it looks for real...

Literally straight screen grabs - not fiddled with (yet!)

**Comment by Andy-ABTec** [comment] 2018-11-03 07:21
OK, got bored...

I've added the "General" tab with a horizontal rip to shorten it and reordered both the navigation and the content to match the tab order.

Please let me know when its "safe" to update the screen grabs again!

**Comment by Andy-ABTec** [comment] 2018-11-03 12:35
Judging by the fact that you've just released RC8 I'm guessing I can update the screen grabs now...

**Comment by Andy-ABTec** [comment] 2018-11-03 14:34
Screen Grabs updated AGAIN!

Just got to check/fiddle with the text now - completed down to RSS / JSON Search tab

**Comment by Andy-ABTec** [comment] 2018-11-03 18:28
@MarkSummerville  having the devils own job getting any functionality out of RSS/JSON search

My RSS link is https://zooqle.com/rss/tv/vnsxpmkce.rss which works in a browser, but that's about as far as it goes,..

The JSON search I'm at a total loss with...

A little help please!

**Comment by SirSparkles** [comment] 2018-11-04 02:21
try these settings
![image](https://user-images.githubusercontent.com/14905881/47959311-70711c80-e01b-11e8-90bb-d2743ab878cd.png)

**Comment by Andy-ABTec** [comment] 2018-11-04 05:47
I would if I could change the URL...

For me the add remove and open buttons do nothing!

Plus it seems that https://eztv.ag/ezrss.xml is blocked when I try to browse it (UK ip with Google DNS) plus, from Wikipedia at least, it world appear the EZTV has gone...

**Comment by SirSparkles** [comment] 2018-11-04 07:08
Try again! Seems like a bug dropped in somewhere.  That link is still up in other parts of the world

Getting problems accessing the zooqle link via the app (works in a browser)

**Comment by Andy-ABTec** [comment] 2018-11-04 09:33
Thanks for the quick response - just re-pulled master and the button functionality is back but still no eztv!
That's obviously a problem here in the UK, because I can now open my original zooqle link from within TVR.

Any insight on how the JSON search works, or at least a little more detail on the content of the text fields please? - I need something for the website.

Other than this I think the Options>Preferences tabs are done...

Just noticed that the Season format in Files and Folders appears to be missing! - was "Season (Season)

**Comment by SirSparkles** [comment] 2018-11-05 02:23
Goes the Zooqle link work? it should search though and initiate a download if it finds something of interest.

The JSON does broadly the same. Ie downloads information from the web and searches through for useful content. It is tightly tied to the EZTV page at the moment though.  Basically the code:
 * Takes the URL from settings
 * appends the IMDB id
 * downloads the data
 * goes to the node indicated by the 'root Note'
 * iterates across items in that node looking for tags with 'Filename Token' and 'Url token'
 * if the filename token looks like it is something useful it downloads the URL token

I'll dig out some JSON as an example

**Comment by Andy-ABTec** [comment] 2018-11-06 06:39
Zooqle appears to be working though I'm not seeing any downloads initiating, may be something else in my preferences.

Thanks for the info on JSON, I'll update the beta site sometime later today. Unfortunately I can't test because I can't get to EZTV. 8-(

**Comment by Andy-ABTec** [comment] 2018-11-07 08:07
@MarkSummerville I've updated RSS/JSON Search as per your information but I'm not particularly happy with it as I cannot prove the RSS is working or test the JSON...

Also please can you confirm that **Files and Folders>Seasons folder format** should default to empty now, it used to contain "Season {Season}"?

**Comment by SirSparkles** [comment] 2018-11-07 13:24
To get the RSS to work you'd need to find missing episodes that are in the RSS. make sure that the title in the RSS feed matches the filename regexs enabled

**Comment by SirSparkles** [comment] 2018-11-07 13:25
Files and Folders>Seasons folder format should stay the same
I'll investigate

**Comment by SirSparkles** [comment] 2018-11-07 13:34
Can't see any reason why the data is removed - can you elaborate on how to reproduce the problem please?

**Comment by Andy-ABTec** [comment] 2018-11-07 14:18
No problem, every time you make changes to preferences and the like I need to update the screen grabs.

To make sure I get "default" settings for the images I delete TVRenameSettings.xml. Effectivly starting me from a clean slate.

If I do this and look look at "Files and Folders" I see: -

![image](https://user-images.githubusercontent.com/5175695/48136514-c225db00-e297-11e8-8e68-0b87e27054ae.png)

As you can see, the field is empty.

If I revert back to an earlier version of the code "Season {Season}" mysteriously appears

**Comment by Andy-ABTec** [comment] 2018-11-07 14:23
> To get the RSS to work you'd need to find missing episodes that are in the RSS. make sure that the title in the RSS feed matches the filename regexs enabled

I'v tried deleting episodes that are in the feed but replacements are offered whether I have RSS enabled or not 😕 

**UPDATE:** It Works! If I delete a recent episode, turn off all the missing episode checks except RSS and run a scan the missing item is reported - So yes, it does work with Zooqle... 😄

**Comment by SirSparkles** [comment] 2018-11-07 23:34
Fixed the default settings (I think) - there were a few that were missing.

Also added new 'super logging' mode for JSON/RSS setup which should help diagnosing RSS/JSON issues

**Comment by Andy-ABTec** [comment] 2018-11-08 06:08
Great, I've updated the Files and Folders screen grab to match.

Just out of interest (and to save me hunting) what other defaults did you tweak?

**Comment by SirSparkles** [comment] 2018-11-08 09:29
https://github.com/TV-Rename/tvrename/commit/d732f94d9cf3057ee07cac291030a3183921da1c

Shows the missing default settings

Did the logging help diagnose the issues?

**Comment by Andy-ABTec** [comment] 2018-11-08 09:52
Dont know I'm afraid, I'd sussed it before you updated the logging...

It suddenly dawned on me that if I turned off all the search methods except RSS and got a hit then RSS must be working - Doh!

**Comment by Andy-ABTec** [comment] 2018-11-08 21:41
OK, I've updated the RSS JSON stuff again, to include the logging.

Please can you check through the Preferences section to make sure I haven't missed or misrepresented anything - I'm guessing you're going to want to update the main website shortly with so many changes and I need another pair of eyes...

**Comment by SirSparkles** [comment] 2018-11-08 22:01
![image](https://user-images.githubusercontent.com/14905881/48197990-5f653a00-e392-11e8-8073-32c8d7fce40b.png)

**Comment by Andy-ABTec** [comment] 2018-11-08 22:09
Just setting up a test for this as I type

**Comment by Andy-ABTec** [comment] 2018-11-08 23:29
Extended Manual>Scan to include the above as it seemed the most logical place to put it...

**Closed as completed** 2018-11-09 15:50 UTC
Labels: Docs update
